apiVersion: v1
kind: Service
metadata:
  name: edgesoft
  labels:
    app: edgesoft
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: edgesoft
    tier: edgesoft
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: edgesoft
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: edgesoft
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edgesoft
  labels:
    app: edgesoft
spec:
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: edgesoft
        tier: edgesoft
    spec:
      containers:
      - image: __IMAGE__
        name: edgesoft
        ports:
        - containerPort: 80
          name: edgesoft
